name: Build GKT

on: [workflow_call]

defaults:
  run:
    shell: bash

jobs:
  build-gkt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build GKT
        run: pnpm tsc && pnpm vite build
        env:
          BUILD_TARGET: gkt
