name: Security Scan
run-name: Security scanning workflow

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          
      - name: Check for vulnerable dependencies (npm)
        run: npm audit --production
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
        
      - name: Check for vulnerable dependencies (Cargo)
        working-directory: ./src-tauri
        run: cargo audit
  
  osv-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install OSV Scanner
        uses: ludeeus/action-setup-osv-scanner@v1.0.0
      
      - name: Run OSV Scanner
        run: osv-scanner -r .
        continue-on-error: true